---
# tasks file for docker-installer
- name: Debian - Install Factorio
  import_tasks: debian.yml
  when: ansible_facts['distribution']|lower == 'debian' and ansible_facts['distribution_major_version']|int >= 8

#- name: Ubuntu - Install Docker CE
#  import_tasks: ubuntu.yml
#  when: ansible_facts['distribution']|lower == 'ubuntu' and ansible_facts['distribution_major_version']|int >= 18
#
#- name: Centos - Install Docker CE
#  import_tasks: centos.yml
#  when: ansible_facts['distribution']|lower == 'centos' and ansible_facts['distribution_major_version']|int >= 8

